name: Docker Build and Push

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-image .

    - name: Push Docker image to Docker Hub
      run: docker push my-image
